Reduce Cognitive Complexity as suggested by SonarQube
kubevirt/ssp-operator pull request #110
Opened 2021-02-02 23:27 UTC by shwetaap

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

2021-02-03 12:35 UTC, akrejcir requested changes
Can you also update the description of this PR and remove all unneeded text?

2021-02-03 12:35 UTC, akrejcir commented on hack/csv-generator.go
> +				switch envVariable.Name {
Can you extract this `switch` block into a function?

2021-03-16 12:34 UTC, ksimon1 commented
@shwetaap can you please address Andrej's feedback?

2021-04-15 09:18 UTC, akrejcir commented
@shwetaap , can you update this PR? It will only take a few minutes and then we can merge it.

2021-07-28 08:27 UTC, dominikholler commented
@vatsalparekh is this PR fixing one of the code smells assigned to you?

2021-07-28 12:46 UTC, vatsalparekh commented
@dominikholler Yes, I'll include this in a new PR

2021-08-30 08:20 UTC, akrejcir commented
/close

2021-08-30 08:20 UTC, closed without merging