docs: Mention auto-import of DataVolumes in README.md
kubevirt/ssp-operator pull request #403
Opened 2022-07-20 15:06 UTC by akrejcir

**What this PR does / why we need it**:
Mentioned that SSP operator deploys resources needed for `DataVolume` auto-import, and fixed outdated information.

**Release note**:
```release-note
None
```

2022-07-21 07:13 UTC, 0xFelix approved these changes

2022-07-25 09:30 UTC, akrejcir commented
Skipping CI, because only `README.md` is changed.

/override ci/prow/e2e-functests
/override ci/prow/e2e-single-node-functests
/override ci/prow/e2e-upgrade-functests

2022-07-25 11:57 UTC, akrejcir commented
I will modify the text more.

/hold

2022-10-24 09:12 UTC, akrejcir commented
/remove-lifecycle stale

2022-12-01 20:40 UTC, lyarwood requested changes
Just a quick suggestion while this is on hold.

2022-12-01 20:40 UTC, lyarwood commented on README.md
> +- DataVolumes for templates - Images are auto-imported to the DataVolumes as specified in the SSP CR.
`DataImportCrons and DataSources for Templates - Images are auto-imported via DataImportCrons to the DataSources as specified in the SSP CR.`?

2023-06-26 11:56 UTC, akrejcir commented
/remove-lifecycle rotten

2023-06-28 12:38 UTC, akrejcir commented
I will return to this later. Closing.

/close

2023-06-28 12:38 UTC, closed without merging