[WIP] ssp operator deletes the node-labeller
kubevirt/ssp-operator pull request #98
Opened 2021-01-20 10:28 UTC by ksimon1

**What this PR does / why we need it**:

**Do not merge. Work in progress. It is missing upgrade test**
ssp operator deletes the node-labeller

This PR updates the reconcile function for node-labeller,
so now it instead of creating/updating deletes all components of labeller.
**Release note**:
```
SSP operator now deletes all node-labeller components, because labeller was moved into Kubevirt.
```
Signed-off-by: Karel Simon <ksimon@redhat.com>

2021-02-16 08:12 UTC, ksimon1 commented
/retest

2021-03-29 10:45 UTC, ksimon1 commented
/retest

2021-03-29 17:14 UTC, sarahbx commented
/lgtm

2021-03-29 17:40 UTC, shwetaap commented
See some sonar cloud failures, otherwise it 
/lgtm

2021-03-29 18:33 UTC, kwiesmueller commented
/lgtm

2021-03-30 08:27 UTC, akrejcir requested changes
Looks good. It just needs functional tests.

2021-03-30 08:27 UTC, akrejcir commented on tests/nodeLabeller_test.go
> -package tests
Instead of removing this file, can you modify it to test that the `node-labeller` resources do not exist? It will be important for upgrade test lane.

2021-03-30 10:36 UTC, akrejcir commented on tests/nodeLabeller_test.go
> +			Expect(err).To(HaveOccurred())
Check that the error is: `errors.IsNotFound(err)`.

2021-03-30 11:20 UTC, akrejcir commented
/lgtm

2021-03-30 11:47 UTC, ksimon1 commented
/approve

2021-03-30 11:48 UTC, merged